# Generated by Django 4.1.3 on 2023-02-24 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='attenedTest',
        ),
    ]
