# Generated by Django 4.1.3 on 2023-02-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0004_remove_marks_student_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='users',
        ),
    ]
