# Generated by Django 4.1.3 on 2023-02-25 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0006_rename_users_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
