# Generated by Django 4.1.3 on 2023-02-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0007_remove_student_password_remove_student_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student',
        ),
    ]
