# Generated by Django 4.1.3 on 2023-02-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0008_remove_student_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='count',
        ),
        migrations.DeleteModel(
            name='marks',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
