# Generated by Django 4.1.3 on 2023-02-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0010_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
