# Generated by Django 4.1.3 on 2023-02-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0012_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='marks',
        ),
        migrations.DeleteModel(
            name='mark',
        ),
    ]
