# Generated by Django 4.1.3 on 2023-02-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0020_mark_student_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='mark',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
