# Generated by Django 4.1.3 on 2023-02-26 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0023_mark_alter_student_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mark',
        ),
    ]
