# Generated by Django 4.1.3 on 2023-03-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0026_alter_student_student_alter_student_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bools',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
