# Generated by Django 4.1.3 on 2023-03-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0027_student_bools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bools',
            field=models.BooleanField(default=False),
        ),
    ]
