# Generated by Django 4.1.3 on 2023-03-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0028_alter_student_bools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Student',
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
